ahoyapi: v2

commands:
  up:
    usage: Run containers
    cmd: "docker-compose up -d"

  build:
    cmd: "docker-compose build"
    usage: Build

  down:
    usage: Destroy containers
    cmd: "docker-compose down"

  stop:
    usage: Stop containers
    cmd: "docker-compose stop"

  console:
    usage: Run symfony commands
    cmd: "docker exec -it $(docker-compose ps -q php) php bin/console $@"

  make:
    usage: Run symfony commands
    cmd: "php bin/console make:$@"

  test:
    usage: Run tests
    cmd: "docker exec -it $(docker-compose ps -q php) php bin/phpunit $@"

  cc:
    cmd: "docker exec -it $(docker-compose ps -q php) php bin/console cache:clear --no-warmup --env=$@"
    usage: Clear cache for a specified environment.

  restart:
    cmd: "docker-compose restart $@"
    usage: Restart the docker-compose containers.

  doctrine:cc:
    cmd: "docker exec -it $(docker-compose ps -q php) php bin/console doctrine:cache:clear-metadata && docker exec -it $(docker-compose ps -q php) php bin/console doctrine:cache:clear-query && docker exec -it $(docker-compose ps -q php) php bin/console doctrine:cache:clear-result"
    usage: Clear cache for a specified environment.

  migrate:
    cmd: "docker exec -it $(docker-compose ps -q php) php bin/console doctrine:migrations:migrate  $@"
    usage: Run console commands doctrine:migrations:migrate.

  migrate:nointeraction:
    cmd: "docker exec -it $(docker-compose ps -q php) php bin/console doctrine:migrations:migrate --no-interaction $@"
    usage: Run console commands doctrine:migrations:migrate.

  schema:force:
    cmd: "docker exec -it $(docker-compose ps -q php) php bin/console doctrine:schema:update  --force --dump-sql"
    usage: Run console commands doctrine:schema:update.

  composer:
    cmd: "docker exec -it $(docker-compose ps -q php) composer $@"
    usage: Run composer commands without having to cd to the project root first.

  db:drop:
    cmd: "docker exec -it $(docker-compose ps -q php) php bin/console --env=dev doctrine:schema:drop --full-database --force"
    usage: Drop all tables

  schema:update:
    usage: Run console commands doctrine:schema:update --force.
    cmd: |
      echo "Clear cache"
      ahoy cc dev
      echo "Clear Doctrine cache"
      ahoy doctrine:cc
      echo "Update Schema"
      ahoy schema:force

  db:rebuild:
    usage: Drop all tables, clear cache and load the data again
    cmd: |
      echo "Drop all tables"
      ahoy db:drop
      echo "Load migrations"
      ahoy migrate:nointeraction
      echo "Update DB schema"
      ahoy schema:force

  db:rebuild-prod:
    usage: Drop all tables, clear cache and load the data again
    cmd: |
      echo "Drop all tables"
      ahoy db:drop
      echo "Load migrations"
      ahoy migrate:nointeraction
      echo "Update DB schema"
      ahoy schema:update
